apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: immich-ml-proxy

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - podmonitor.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: immich-ml-proxy
      app.kubernetes.io/component: proxy
