apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: immich-ml-proxy
  namespace: immich-ml-proxy
  labels:
    app.kubernetes.io/name: immich-ml-proxy
    app.kubernetes.io/component: proxy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: immich-ml-proxy
  podMetricsEndpoints:
    - port: http
      interval: 10s
      path: /metrics
