apiVersion: v1
kind: Service
metadata:
  name: immich-ml-proxy
  namespace: immich-ml-proxy
  labels:
    app.kubernetes.io/name: immich-ml-proxy
    app.kubernetes.io/component: proxy
spec:
  ports:
    - name: http
      port: 3003
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: immich-ml-proxy
